/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { AssetDevice } from "./assetDevice";
import type { AssetLastMessage } from "./assetLastMessage";
import type { AssetLastPositionMessage } from "./assetLastPositionMessage";

export interface Asset {
  /** @minLength 1 */
  chasisNumber: string;
  /** @nullable */
  device?: AssetDevice;
  gpsInactive?: boolean;
  hasActiveSeizure?: boolean;
  /** @minLength 1 */
  id: string;
  isDelayed?: boolean;
  /** @nullable */
  lastMessage?: AssetLastMessage;
  /** @nullable */
  lastPositionMessage?: AssetLastPositionMessage;
  maxSpeed: number;
  /** @minLength 1 */
  name: string;
  online: boolean;
  /** @minLength 1 */
  organizationId: string;
  /** @nullable */
  seizureExpirationDate?: string | null;
}
