/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */
import type { SendGpsCommandParameters } from "./sendGpsCommandParameters";

export interface SendGpsCommand {
  /** @minLength 1 */
  commandType: string;
  /** @nullable */
  parameters?: SendGpsCommandParameters;
}
