/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Navtrack.Api
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateAsset {
  /** @minLength 1 */
  chasisNumber: string;
  /** @nullable */
  hasActiveSeizure?: boolean | null;
  name?: string;
  /** @nullable */
  seizureExpirationDate?: string | null;
}
