name: Publish Docker Images

on:
  release:
    types: [released]

env:
  version: ${GITHUB_REF_NAME#v}

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  publish:
    if: github.repository == 'navtrack/navtrack'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build
        run: |
          ./build-docker-images.sh
      - name: Docker tag
        run: |
          docker tag navtrack/api ghcr.io/navtrack/navtrack/api:latest
          docker tag navtrack/api ghcr.io/navtrack/navtrack/api:${{ env.version }}
          docker tag navtrack/web ghcr.io/navtrack/navtrack/web:latest
          docker tag navtrack/web ghcr.io/navtrack/navtrack/web:${{ env.version }}
          docker tag navtrack/listener ghcr.io/navtrack/navtrack/listener:latest
          docker tag navtrack/listener ghcr.io/navtrack/navtrack/listener:${{ env.version }}
      - name: Docker push
        run: |
          docker push --all-tags ghcr.io/navtrack/navtrack/api
          docker push --all-tags ghcr.io/navtrack/navtrack/web
          docker push --all-tags ghcr.io/navtrack/navtrack/listener
